### PR TITLE
fix auth wait and create missing tables on start

### LINKED ISSUE #38: Do not require manual initialization of data
The backend currently requires some manual setup to be done in the database.
Make the backend create all needed tables etc.

### PR DESCRIPTION
**Pull request by aboft**
sends PASS instead of messaging nickserv. Also corrected the TopWord parse in Sender.ts to prevent parsing whole numbers as a top word.

### CODE REVIEW

**Review by maxaudron — APPROVED** [review]

File: backend/irc/utils/db/InitDatabase.ts [hunk 1]
```diff
@@ -0,0 +1,61 @@
+import knex from './dbConn';
+
+class InitDatabase {
```
Comment (LoLei) [inline backend/irc/utils/db/InitDatabase.ts:3]: Class names should ideally be nouns.

**Review by LoLei — APPROVED** [review]
